### ISSUE TITLE
Kepler instance creation failed 

### ISSUE THREAD

**Issue by rinana** [sustainable-computing-io/kepler-operator#103]
Hello,
I deployed kepler-operator v0.5.0 from OpenShift OperatorHub UI and
when I tried to create a Kepler instance w/ the operator, the following error occurred....

OpenShift version: 4.11.1

```
TypeError: n.filter is not a function
    at Y (https://url/static/operand-chunk-73b589536f00fd472657.min.js:1:2617)
    at Q (https://url/static/operand-chunk-73b589536f00fd472657.min.js:1:3054)
    at na (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:254:58879)
    at Hs (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:254:111315)
    at xc (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:254:98327)
    at Cc (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:254:98255)
    at _c (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:254:98118)
    at pc (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:254:95105)
    at https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:254:44774
    at t.unstable_runWithPriority (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:262:3768)
```

Component traces:
<details> 
```
at Q (https://url/static/operand-chunk-73b589536f00fd472657.min.js:1:3040)
    at td
    at M (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:862756)
    at Z (https://url/static/operand-chunk-73b589536f00fd472657.min.js:1:3361)
    at Row
    at https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:863287
    at tr
    at j (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:862245)
    at t (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:141:72032)
    at tbody
    at table
    at m (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:233:141869)
    at s (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:238:115889)
    at D (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:863378)
    at div
    at div
    at t (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:93:65470)
    at t (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:92:43222)
    at o (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:878335)
    at div
    at L (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:863037)
    at div
    at div
    at _ (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:185070)
    at N (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:185518)
    at div
    at U (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:864548)
    at ee (https://url/static/operand-chunk-73b589536f00fd472657.min.js:1:4241)
    at div
    at t.a (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1206179)
    at t.a (https://url/static/ceph-storage-plugin/code-refs/resourceDetailsPage~clusterserviceversion~create-operand~odf-system-li~628b6b41-chunk-d6ba8a0498c3df9fc5d3.min.js:1:16109)
    at ae (https://url/static/operand-chunk-73b589536f00fd472657.min.js:1:8158)
    at o (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:529089)
    at t (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:21:58048)
    at t (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:21:60093)
    at Suspense
    at div
    at _ (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:185070)
    at N (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:185518)
    at div
    at https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:957033
    at p.memo.t.children.e.children.t.reduxes.e.reduxes.t.reduxes.every.reduxID (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:562115)
    at S (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:93:80440)
    at <anonymous> (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:564403)
    at S (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:93:80440)
    at https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1145479
    at o (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:529089)
    at DetailsPage
    at ye (https://url/static/clusterserviceversion-chunk-c8ff3faf65261572161b.min.js:1:47283)
    at s (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:278162)
    at https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:622009
    at S (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:93:80440)
    at t (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:21:58048)
    at t (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:21:60093)
    at Suspense
    at o (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:529089)
    at section
    at f (https://url/static/vendor-patternfly-core-chunk-006bb1499791fa7cfea7.min.js:5:476199)
    at div
    at div
    at t.a (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1657130)
    at div
    at div
    at c (https://url/static/vendor-patternfly-core-chunk-006bb1499791fa7cfea7.min.js:5:293886)
    at d (https://url/static/vendor-patternfly-core-chunk-006bb1499791fa7cfea7.min.js:1:61446)
    at div
    at d (https://url/static/vendor-patternfly-core-chunk-006bb1499791fa7cfea7.min.js:5:349163)
    at l (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1296447)
    at https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:534541
    at S (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:93:80440)
    at main
    at div
    at E (https://url/static/vendor-patternfly-core-chunk-006bb1499791fa7cfea7.min.js:5:47942)
    at div
    at div
    at c (https://url/static/vendor-patternfly-core-chunk-006bb1499791fa7cfea7.min.js:1:136023)
    at div
    at div
    at c (https://url/static/vendor-patternfly-core-chunk-006bb1499791fa7cfea7.min.js:5:293886)
    at d (https://url/static/vendor-patternfly-core-chunk-006bb1499791fa7cfea7.min.js:1:61446)
    at div
    at d (https://url/static/vendor-patternfly-core-chunk-006bb1499791fa7cfea7.min.js:5:349163)
    at On (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:36:186146)
    at t.default (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:973832)
    at t.default (https://url/static/quick-start-chunk-8e73f5b9e0f856b576ca.min.js:1:1260)
    at s (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:278162)
    at t.a (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1738384)
    at Z (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1740514)
    at st (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:36:146439)
    at Z (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1740514)
    at Z (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1740514)
    at t.a (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1734330)
    at c (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1731733)
    at t.a (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1734141)
    at X (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1740644)
    at https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1743398
    at r (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:36:126245)
    at t (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:21:58048)
    at t (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:21:60093)
    at t (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:21:54653)
    at te (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1743708)
    at t.a (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:895415)
    at t.a (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:1205815)
    at s (https://url/static/main-chunk-525818b154a57a9b220a.min.js:1:707057)
    at t.a (https://url/static/vendors~main-chunk-40fab65853dff2fbc413.min.js:141:538452)
    at Suspense
    ```
    </details>

**Comment by sthaha** [comment]
That is a bug in Openshift UI which is fixed in 4.13 (which is the supported openshift version to use) 
Could you please confirm if the kepler daemonset  is deployed and running ? 
If it is not, could you please provide us the operator logs ?

**Comment by rinana** [comment]
Thanks for your comments. kepler daemonset is not deployed.
The operator only deployed successfully kepler crd, scc, cr, clusterrole and clusterrolebinding.

Here is the operator's log:
```
% oc logs -n openshift-operators kepler-operator-controller-manager-fdf477d97-n9zgq 
I0724 01:59:28.329010       1 request.go:682] Waited for 1.030882654s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/authorization.k8s.io/v1?timeout=32s
2023-07-24T01:59:32Z	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": "127.0.0.1:8080"}
2023-07-24T01:59:32Z	INFO	setup	starting manager
2023-07-24T01:59:32Z	INFO	Starting server	{"kind": "health probe", "addr": "[::]:8081"}
I0724 01:59:32.829636       1 leaderelection.go:248] attempting to acquire leader lease openshift-operators/0d9cbc82.sustainable.computing.io...
2023-07-24T01:59:32Z	INFO	Starting server	{"path": "/metrics", "kind": "metrics", "addr": "127.0.0.1:8080"}
I0724 01:59:49.873329       1 leaderelection.go:258] successfully acquired lease openshift-operators/0d9cbc82.sustainable.computing.io
2023-07-24T01:59:49Z	INFO	Starting EventSource	{"controller": "kepler", "controllerGroup": "kepler.system.sustainable.computing.io", "controllerKind": "Kepler", "source": "kind source: *v1alpha1.Kepler"}
2023-07-24T01:59:49Z	INFO	Starting EventSource	{"controller": "kepler", "controllerGroup": "kepler.system.sustainable.computing.io", "controllerKind": "Kepler", "source": "kind source: *v1.PersistentVolume"}
2023-07-24T01:59:49Z	DEBUG	events	kepler-operator-controller-manager-fdf477d97-n9zgq_721a45f1-617e-4e9e-8e69-2ecc16c29bdf became leader	{"type": "Normal", "object": {"kind":"Lease","namespace":"openshift-operators","name":"0d9cbc82.sustainable.computing.io","uid":"eaae1634-6717-4b29-811a-10a02b49f695","apiVersion":"coordination.k8s.io/v1","resourceVersion":"280984196"}, "reason": "LeaderElection"}
2023-07-24T01:59:49Z	INFO	Starting EventSource	{"controller": "kepler", "controllerGroup": "kepler.system.sustainable.computing.io", "controllerKind": "Kepler", "source": "kind source: *v1.PersistentVolumeClaim"}
2023-07-24T01:59:49Z	INFO	Starting EventSource	{"controller": "kepler", "controllerGroup": "kepler.system.sustainable.computing.io", "controllerKind": "Kepler", "source": "kind source: *v1.ConfigMap"}
2023-07-24T01:59:49Z	INFO	Starting EventSource	{"controller": "kepler", "controllerGroup": "kepler.system.sustainable.computing.io", "controllerKind": "Kepler", "source": "kind source: *v1.Service"}
2023-07-24T01:59:49Z	INFO	Starting EventSource	{"controller": "kepler", "controllerGroup": "kepler.system.sustainable.computing.io", "controllerKind": "Kepler", "source": "kind source: *v1.Deployment"}
2023-07-24T01:59:49Z	INFO	Starting EventSource	{"controller": "kepler", "controllerGroup": "kepler.system.sustainable.computing.io", "controllerKind": "Kepler", "source": "kind source: *v1.ServiceAccount"}
2023-07-24T01:59:49Z	INFO	Starting EventSource	{"controller": "kepler", "controllerGroup": "kepler.system.sustainable.computing.io", "controllerKind": "Kepler", "source": "kind source: *v1.Role"}
2023-07-24T01:59:49Z	INFO	Starting EventSource	{"controller": "kepler", "controllerGroup": "kepler.system.sustainable.computing.io", "controllerKind": "Kepler", "source": "kind source: *v1.ClusterRole"}
2023-07-24T01:59:49Z	INFO	Starting EventSource	{"controller": "kepler", "controllerGroup": "kepler.system.sustainable.computing.io", "controllerKind": "Kepler", "source": "kind source: *v1.ClusterRoleBinding"}
2023-07-24T01:59:49Z	INFO	Starting EventSource	{"controller": "kepler", "controllerGroup": "kepler.system.sustainable.computing.io", "controllerKind": "Kepler", "source": "kind source: *v1.RoleBinding"}
2023-07-24T01:59:49Z	INFO	Starting Controller	{"controller": "kepler", "controllerGroup": "kepler.system.sustainable.computing.io", "controllerKind": "Kepler"}
2023-07-24T01:59:51Z	INFO	Starting workers	{"controller": "kepler", "controllerGroup": "kepler.system.sustainable.computing.io", "controllerKind": "Kepler", "worker count": 1}
2023-07-24T02:00:11Z	DEBUG	ConfigMap reconciled	{"kepler": "kepler/kepler", "method": "Collector", "configmap": "kepler/kepler-exporter-cfm", "OperationResult": "created"}
2023-07-24T02:00:11Z	DEBUG	kepler-exporter service reconciled	{"kepler": "kepler/kepler", "method": "Collector", "Service": "kepler/kepler-exporter", "OperationResult": "created"}
2023-07-24T02:00:11Z	DEBUG	ServiceAccount reconciled	{"kepler": "kepler/kepler", "method": "Collector", "ServiceAccount": "kepler/kepler-sa", "operation": "created"}
2023-07-24T02:00:11Z	DEBUG	ClusterRole	{"kepler": "kepler/kepler", "method": "Collector", "kepler-clusterrole": "kepler-clusterrole", "clusterRole": {"name": "kepler-clusterrole"}}
2023-07-24T02:00:11Z	DEBUG	ClusterRoleBinding reconciled	{"kepler": "kepler/kepler", "method": "Collector", "RoleBinding": "/kepler-clusterrole-binding", "clusterRoleBinding": {"name": "kepler-clusterrole-binding"}}
2023-07-24T02:00:11Z	DEBUG	SecurityContextConstraints	{"kepler": "kepler/kepler", "method": "Collector", "securityContextConstraints": "kepler/kepler-scc", "SecurityContextConstraints": {"metadata":{"name":"kepler-scc","uid":"73a7721b-9a4f-453c-826d-93f699090372","resourceVersion":"280987695","generation":1,"creationTimestamp":"2023-07-24T02:00:11Z","labels":{"sustainable-computing.io/app":"kepler"},"managedFields":[{"manager":"manager","operation":"Update","apiVersion":"security.openshift.io/v1","time":"2023-07-24T02:00:11Z","fieldsType":"FieldsV1","fieldsV1":{"f:allowHostDirVolumePlugin":{},"f:allowHostIPC":{},"f:allowHostNetwork":{},"f:allowHostPID":{},"f:allowHostPorts":{},"f:allowPrivilegedContainer":{},"f:allowedCapabilities":{},"f:defaultAddCapabilities":{},"f:fsGroup":{".":{},"f:type":{}},"f:groups":{},"f:metadata":{"f:labels":{".":{},"f:sustainable-computing.io/app":{}}},"f:priority":{},"f:readOnlyRootFilesystem":{},"f:requiredDropCapabilities":{},"f:runAsUser":{".":{},"f:type":{}},"f:seLinuxContext":{".":{},"f:type":{}},"f:supplementalGroups":{},"f:users":{},"f:volumes":{}}}]},"priority":null,"allowPrivilegedContainer":true,"defaultAddCapabilities":["SYS_ADMIN"],"requiredDropCapabilities":null,"allowedCapabilities":null,"allowHostDirVolumePlugin":true,"volumes":["configMap","emptyDir","hostPath","projected"],"allowHostNetwork":true,"allowHostPorts":true,"allowHostPID":true,"allowHostIPC":true,"allowPrivilegeEscalation":true,"seLinuxContext":{"type":"RunAsAny"},"runAsUser":{"type":"RunAsAny"},"supplementalGroups":{"type":"RunAsAny"},"fsGroup":{"type":"RunAsAny"},"readOnlyRootFilesystem":true,"users":["kepler","system:serviceaccount:kepler:kepler-sa"],"groups":[]}}
2023-07-24T02:00:11Z	DEBUG	DaemonSet Image	{"kepler": "kepler/kepler", "method": "Collector", "daemonSet": "kepler/kepler-exporter", "image": "quay.io/sustainable_computing_io/kepler:latest"}
2023-07-24T02:00:11Z	DEBUG	Daemonset reconciled	{"kepler": "kepler/kepler", "method": "Collector", "daemonSet": "kepler/kepler-exporter", "OperationResult": "created"}
2023-07-24T02:00:11Z	DEBUG	ConfigMap reconciled	{"kepler": "kepler/kepler", "method": "Collector", "configmap": "kepler/kepler-exporter-cfm", "OperationResult": "unchanged"}
2023-07-24T02:00:11Z	DEBUG	kepler-exporter service reconciled	{"kepler": "kepler/kepler", "method": "Collector", "Service": "kepler/kepler-exporter", "OperationResult": "updated"}
2023-07-24T02:00:11Z	DEBUG	ServiceAccount reconciled	{"kepler": "kepler/kepler", "method": "Collector", "ServiceAccount": "kepler/kepler-sa", "operation": "unchanged"}
2023-07-24T02:00:11Z	DEBUG	ClusterRole	{"kepler": "kepler/kepler", "method": "Collector", "kepler-clusterrole": "kepler-clusterrole", "clusterRole": {"name": "kepler-clusterrole"}}
2023-07-24T02:00:11Z	DEBUG	ClusterRoleBinding reconciled	{"kepler": "kepler/kepler", "method": "Collector", "RoleBinding": "/kepler-clusterrole-binding", "clusterRoleBinding": {"name": "kepler-clusterrole-binding"}}
2023-07-24T02:00:11Z	DEBUG	SecurityContextConstraints	{"kepler": "kepler/kepler", "method": "Collector", "securityContextConstraints": "kepler/kepler-scc", "SecurityContextConstraints": {"kind":"SecurityContextConstraints","apiVersion":"security.openshift.io/v1","metadata":{"name":"kepler-scc","namespace":"kepler","creationTimestamp":null,"labels":{"sustainable-computing.io/app":"kepler"}},"priority":null,"allowPrivilegedContainer":true,"defaultAddCapabilities":["SYS_ADMIN"],"requiredDropCapabilities":null,"allowedCapabilities":null,"allowHostDirVolumePlugin":true,"volumes":["configMap","projected","emptyDir","hostPath"],"allowHostNetwork":true,"allowHostPorts":true,"allowHostPID":true,"allowHostIPC":true,"seLinuxContext":{"type":"RunAsAny"},"runAsUser":{"type":"RunAsAny"},"supplementalGroups":{},"fsGroup":{"type":"RunAsAny"},"readOnlyRootFilesystem":true,"users":["kepler","system:serviceaccount:kepler:kepler-sa"],"groups":null}}
2023-07-24T02:00:11Z	DEBUG	DaemonSet Image	{"kepler": "kepler/kepler", "method": "Collector", "daemonSet": "kepler/kepler-exporter", "image": "quay.io/sustainable_computing_io/kepler:latest"}
2023-07-24T02:00:11Z	DEBUG	Daemonset reconciled	{"kepler": "kepler/kepler", "method": "Collector", "daemonSet": "kepler/kepler-exporter", "OperationResult": "updated"}
```

**Comment by rinana** [comment]
I deleted the instance and recreated it again, the daemonset is deployed at this time/
(seems that it just took longer time to deploy...)

Thanks for your help. I closed the issue.

**Comment by husky-parul** [comment]
@rinana We recommend OCP version >= 4.13
Version previous to 4.13 would need Machine Configs for cgroup v2 if they are not enabled. Machine Config support has been deprecated from kepler-operator:0.5.0 onward.

**Comment by rinana** [comment]
@husky-parul 
I see.... Thank you for recommendation. I'll ask to upgrade OCP version.
